### ISSUE TITLE
ggcorr errors out on matrix

### ISSUE THREAD

**Issue by maxheld83** [briatte/ggcorr#1]
it would appear that `ggcorr` doesn't like matrices.

```
ggcorr(data.matrix(nba[,-1]))
```

yields:

```
Error in cor(data[1:ncol(data)], use = method) : 
  supply both 'x' and 'y' or a matrix-like 'x'
```

That seems odd, because the documentation says something matrix-like is expected, which in this case, I have actually supplied.

**Comment by briatte** [comment]
This is a bug, working on it (not easy because of the `geom = "circle"` option, which is tricky).

**Comment by maxheld83** [comment]
great, thanks!
Fantastic work, btw, I love using `ggplot2` for all graphs.

**Comment by schloerke** [comment]
closed in [ggobi/ggally#69](https://github.com/ggobi/ggally/issues/69)

**Comment by maxheld83** [comment]
yup, this also works now. Great! Thanks for the fast fix.

**Comment by maxheld83** [comment]
is it possible this is still not on `GGally` via CRAN?
I'd love to use the function, but only manually taking it from here works.
