### ISSUE TITLE
Include significance levels

### ISSUE THREAD

**Issue by guilhermeparreira** [briatte/ggcorr#16]
Hi There! I would like to make a request because I found your graph more beautiful than `corrplot` and I am looking forward to use it in a new project.

I would like to include information of `p-values` in the right upper corner of each correlation. Or a "X" above the correlation number that it is not significant. Or even, change the color (or any other style argument) of the correlation parameter.

These are just some ideas and suggestion.

Thank you

**Comment by njudd** [comment]
It seems unsupported at this moment in time.
See: https://github.com/briatte/ggcorr/issues/8

**Comment by briatte** [comment]
Hi @guilhermeparreira -- Just to confirm that indeed, significance levels are not supported by `ggcorr`. Perhaps `ggcorrplot` or the `corrr` package can help in that respect.
