### ISSUE TITLE
have ggcorr accept cor results

### ISSUE THREAD

**Issue by maxheld83** [briatte/ggcorr#2]
... would be nice if I could just pass cor results to ggcorr (as it is the case in `corrplot`) – that gives users more options for which correlation coefficient to use etc.

**Comment by briatte** [comment]
This is a bug, working on it (not easy because of the `geom = "circle"` option, which is tricky).

**Comment by schloerke** [comment]
closed in [ggobi/ggally#68](https://github.com/ggobi/ggally/issues/68)

**Comment by maxheld83** [comment]
this works great. (own correlation matrix, I mean)
