### ISSUE TITLE
make color continuous

### ISSUE THREAD

**Issue by maxheld83** [briatte/ggcorr#3]
... maybe as an option?

Since the correlation coefficients _are_, in fact, continuous information.

**Comment by briatte** [comment]
The issue with this is that ggplot2 does not let you bind the colors to fixed points, so the same color spectrum might correspond to different ranges. This also happens with the current way that the function works, using quantiles.

Working on it.

**Comment by briatte** [comment]
@maxheld83 could you please try the development version that I just committed to this repo?

The default behaviour is now to make the color continuous. It works with both `geom = "circle"` and `geom = "point"`.

When using continuous scaling, the default is to use a red-yellow-green gradient that goes from –1 to +1 and is centered at 0. You can modify that through the `low`, `mid` and `high` arguments, plus `midpoint` to change the midpoint, and if you set `midpoint` to `NULL`, the function will use the median correlation coefficient. Finally, if you do not want the continuous scale to range from –1 to +1, set `limits` to `FALSE`.

Examples:

``` r
nba <- read.csv("http://datasets.flowingdata.com/ppg2008.csv")
# points
ggcorr(nba[, -1])
# points, discrete scale
ggcorr(nba[, -1], nbreaks = 4)
# circles
ggcorr(nba[, -1], geom = "circle")
# circles, discrete scale
ggcorr(nba[, -1], geom = "point", nbreaks = 4)
```

Returns, in that order:

![ggcorr1](https://cloud.githubusercontent.com/assets/322533/6465309/909fe004-c1c0-11e4-9fe1-36d2b9f18586.png)
![ggcorr2](https://cloud.githubusercontent.com/assets/322533/6465310/90a18b5c-c1c0-11e4-8753-e4665039693c.png)
![ggcorr3](https://cloud.githubusercontent.com/assets/322533/6465311/90a4437e-c1c0-11e4-851b-264f249d3b32.png)
![ggcorr4](https://cloud.githubusercontent.com/assets/322533/6465312/90a67dce-c1c0-11e4-803d-23619f18af0e.png)

``` r
# custom options
ggcorr(nba[, -1], geom = "point", mid = "white", high = "#4575b4", limits = FALSE)
```

![ggcorr5](https://cloud.githubusercontent.com/assets/322533/6465536/06c1af46-c1c2-11e4-9dc2-f48f09ed9d6a.png)

**Comment by maxheld83** [comment]
wow looks great @briatte, I'll try it later today.
I'm a bit confused about the repos – should I try this here, or the `dev` branch of [`ggally`](https://github.com/ggobi/ggally/commits/dev), which seems to have fixed #1 and #2?

**Comment by briatte** [comment]
The confusion is my fault.

You should use this repo. I have also fixed #1 and #2 in it.

**Comment by maxheld83** [comment]
just tried it and it worked great @briatte , even added the `label=TRUE`.
now I can get rid of my non-ggplot2 version.
Hope this makes it to CRAN soon!

**Comment by briatte** [comment]
Thanks, will commit to GGally quickly.
