### ISSUE TITLE
labels with spaces cause NAs

### ISSUE THREAD

**Issue by maxheld83** [briatte/ggcorr#4]
I have a dataset with some colnames like `Test Res`, and it turns out that for every colname that includes a space, `ggcorr` drops all the correlations and gives this error:

```
Warning message:
Removed 27 rows containing missing values (geom_text). 
```

**Comment by briatte** [comment]
The [most recent commit](https://github.com/briatte/ggcorr/commit/b259d0cfbe2c4518dbac0e15826948af06486ab8) should fix that.
