### ISSUE TITLE
Not accepting already computed correlation matrix

### ISSUE THREAD

**Issue by aalokjha** [briatte/ggcorr#7]
Hi 

Thanks a lot for putting this together. I already have correlation matrix computed and stored in a data frame. I tried passing that in the `ggcorr` by `ggcorr(data = NULL, cor_matrix = mn[,-1])` here `mn` is the data frame which has the correlation matrix with first column having the variable names in its rows. However, it throws the following error. Can you please help me with this. 

```
Error in 1:ncol(data) : argument of length 0
```

Thanks!

Alok

**Comment by briatte** [comment]
Hi—

I'm afraid that I cannot solve that issue without looking at your data. There is no call to `ncol` in the `ggcorr` function, so I need to understand your input to solve that one.

Please show me at least some extract of your data.
