### ISSUE TITLE
Plotting only significant values

### ISSUE THREAD

**Issue by aterhorst** [briatte/ggcorr#8]
How can I plot only significant correlations?

**Comment by briatte** [comment]
I have not implemented anything in `ggcorr` that might handle _p_-values, as I recommend against looking at _p_-values for correlation coefficients. Could you please confirm that this is what you are looking for?

**Comment by aterhorst** [comment]
Thanks for getting back to me Francoisn

Yup. I refer to this web page which explains how to do this in corrplot. I am sure you are aware of this site:

http://www.sthda.com/english/wiki/visualize-correlation-matrix-using-correlogram

Cheers

## 

Andrew Terhorsthttp://people.csiro.au/T/A/Andrew-Terhorst.aspx
Open Innovation Researcher
Sandy Bay Location Leader

DATA61 | CSIRO
E andrew.terhorst@data61.csiro.aumailto:andrew.terhorst@data61.csiro.au T +613 6237 5562   M +61 400 869 594
15 College Road, Sandy Bay, TAS 7005 www.data61.csiro.auhttp://www.data61.csiro.au/
research.csiro.au/innovationhttp://research.csiro.au/innovation

CSIRO’s Digital Productivity business unit and NICTA have joined forces to create digital powerhouse Data61
[cid:image001.png@01D1C2F5.AC6F5AD0]

**Comment by briatte** [comment]
Okay, I see what you mean.

I would prefer not to push `ggcorr` towards looking at _p_-values for (Pearson) correlation coefficients. I am a huge partisan of sticking with magnitude rather than trusting statistical significance in many circumstances.

**Comment by aterhorst** [comment]
No worries. I am not expert in statistics so defer to your judgement. Thanks for getting back to me.

## 

Andrew Terhorsthttp://people.csiro.au/T/A/Andrew-Terhorst.aspx
Open Innovation Researcher
Sandy Bay Location Leader

DATA61 | CSIRO
E andrew.terhorst@data61.csiro.aumailto:andrew.terhorst@data61.csiro.au T +613 6237 5562   M +61 400 869 594
15 College Road, Sandy Bay, TAS 7005 www.data61.csiro.auhttp://www.data61.csiro.au/
research.csiro.au/innovationhttp://research.csiro.au/innovation

CSIRO’s Digital Productivity business unit and NICTA have joined forces to create digital powerhouse Data61
[cid:image001.png@01D1C2FB.E3361FD0]

**Comment by briatte** [comment]
I am no expert either, but if `r` is high but statistically insignificant (or the reverse situation), then the joint distribution of values that you are looking at is probably violating some of the core assumptions of linear correlation—in which case you want a scatterplot to understand what's going on.

Except on small-_n_ samples, you should expect moderate-high correlation coefficients (say, _r_ > 0.3) to have a _p_-value above conventional levels of statistical significance. At least that's what I have observed in practice on various datasets of _N_ ~ 50-500 observations.

**Comment by njudd** [comment]
This is a pretty useful feature & there are circumstances where it is justified. You could even take the MCC corrected ones from `psych::corr.test`. It is a shame this feature is not supported as there aren't many out of the box good ggplot corr packages.

**Comment by briatte** [comment]
@njudd @aterhorst Perhaps look at `{ggcorrplot}` for a feature that seems to come close to what you need?

https://cran.r-project.org/package=ggcorrplot
