### ISSUE TITLE
Changing the Diagonal Text Label Size

### ISSUE THREAD

**Issue by moaraj** [briatte/ggcorr#9]
Hello, I have tried using 
`theme(text = element_text(size = 0, hjust = -1))`
but cannot change the size of the labels. Is there another way that was not stated in the vignette?

**Comment by briatte** [comment]
Hi @moaraj 

Are your referring to the variable labels? In that case, [this part of the vignette](https://briatte.github.io/ggcorr/#controlling-the-variable-labels) should help.

Please let me know if that works, and sorry for answering this question so very, very late.
